-- ForgeHouse 50 — reading calendar seed (generated; do not hand-edit dates)
DELETE FROM reading_assignments;
DELETE FROM reading_days;
INSERT INTO reading_days (day_number, date, label) VALUES (1, '2026-09-07', 'Reading Day 1');
INSERT INTO reading_assignments (id, day_number, book, chapter_start, chapter_end, chapter_count, est_minutes) VALUES ('ra-1-matthew-1', 1, 'Matthew', 1, 6, 6, 24);
INSERT INTO reading_days (day_number, date, label) VALUES (2, '2026-09-09', 'Reading Day 2');
INSERT INTO reading_assignments (id, day_number, book, chapter_start, chapter_end, chapter_count, est_minutes) VALUES ('ra-2-matthew-7', 2, 'Matthew', 7, 12, 6, 24);
INSERT INTO reading_days (day_number, date, label) VALUES (3, '2026-09-10', 'Reading Day 3');
INSERT INTO reading_assignments (id, day_number, book, chapter_start, chapter_end, chapter_count, est_minutes) VALUES ('ra-3-matthew-13', 3, 'Matthew', 13, 18, 6, 24);
INSERT INTO reading_days (day_number, date, label) VALUES (4, '2026-09-12', 'Reading Day 4');
INSERT INTO reading_assignments (id, day_number, book, chapter_start, chapter_end, chapter_count, est_minutes) VALUES ('ra-4-matthew-19', 4, 'Matthew', 19, 24, 6, 24);
INSERT INTO reading_days (day_number, date, label) VALUES (5, '2026-09-13', 'Reading Day 5');
INSERT INTO reading_assignments (id, day_number, book, chapter_start, chapter_end, chapter_count, est_minutes) VALUES ('ra-5-matthew-25', 5, 'Matthew', 25, 28, 4, 16);
INSERT INTO reading_assignments (id, day_number, book, chapter_start, chapter_end, chapter_count, est_minutes) VALUES ('ra-5-mark-1', 5, 'Mark', 1, 2, 2, 10);
INSERT INTO reading_days (day_number, date, label) VALUES (6, '2026-09-14', 'Reading Day 6');
INSERT INTO reading_assignments (id, day_number, book, chapter_start, chapter_end, chapter_count, est_minutes) VALUES ('ra-6-mark-3', 6, 'Mark', 3, 8, 6, 24);
INSERT INTO reading_days (day_number, date, label) VALUES (7, '2026-09-16', 'Reading Day 7');
INSERT INTO reading_assignments (id, day_number, book, chapter_start, chapter_end, chapter_count, est_minutes) VALUES ('ra-7-mark-9', 7, 'Mark', 9, 14, 6, 24);
INSERT INTO reading_days (day_number, date, label) VALUES (8, '2026-09-17', 'Reading Day 8');
INSERT INTO reading_assignments (id, day_number, book, chapter_start, chapter_end, chapter_count, est_minutes) VALUES ('ra-8-mark-15', 8, 'Mark', 15, 16, 2, 10);
INSERT INTO reading_assignments (id, day_number, book, chapter_start, chapter_end, chapter_count, est_minutes) VALUES ('ra-8-luke-1', 8, 'Luke', 1, 4, 4, 16);
INSERT INTO reading_days (day_number, date, label) VALUES (9, '2026-09-19', 'Reading Day 9');
INSERT INTO reading_assignments (id, day_number, book, chapter_start, chapter_end, chapter_count, est_minutes) VALUES ('ra-9-luke-5', 9, 'Luke', 5, 10, 6, 24);
INSERT INTO reading_days (day_number, date, label) VALUES (10, '2026-09-20', 'Reading Day 10');
INSERT INTO reading_assignments (id, day_number, book, chapter_start, chapter_end, chapter_count, est_minutes) VALUES ('ra-10-luke-11', 10, 'Luke', 11, 16, 6, 24);
INSERT INTO reading_days (day_number, date, label) VALUES (11, '2026-09-21', 'Reading Day 11');
INSERT INTO reading_assignments (id, day_number, book, chapter_start, chapter_end, chapter_count, est_minutes) VALUES ('ra-11-luke-17', 11, 'Luke', 17, 21, 5, 20);
INSERT INTO reading_days (day_number, date, label) VALUES (12, '2026-09-23', 'Reading Day 12');
INSERT INTO reading_assignments (id, day_number, book, chapter_start, chapter_end, chapter_count, est_minutes) VALUES ('ra-12-luke-22', 12, 'Luke', 22, 24, 3, 12);
INSERT INTO reading_assignments (id, day_number, book, chapter_start, chapter_end, chapter_count, est_minutes) VALUES ('ra-12-john-1', 12, 'John', 1, 2, 2, 10);
INSERT INTO reading_days (day_number, date, label) VALUES (13, '2026-09-24', 'Reading Day 13');
INSERT INTO reading_assignments (id, day_number, book, chapter_start, chapter_end, chapter_count, est_minutes) VALUES ('ra-13-john-3', 13, 'John', 3, 7, 5, 20);
INSERT INTO reading_days (day_number, date, label) VALUES (14, '2026-09-26', 'Reading Day 14');
INSERT INTO reading_assignments (id, day_number, book, chapter_start, chapter_end, chapter_count, est_minutes) VALUES ('ra-14-john-8', 14, 'John', 8, 12, 5, 20);
INSERT INTO reading_days (day_number, date, label) VALUES (15, '2026-09-27', 'Reading Day 15');
INSERT INTO reading_assignments (id, day_number, book, chapter_start, chapter_end, chapter_count, est_minutes) VALUES ('ra-15-john-13', 15, 'John', 13, 17, 5, 20);
INSERT INTO reading_days (day_number, date, label) VALUES (16, '2026-09-28', 'Reading Day 16');
INSERT INTO reading_assignments (id, day_number, book, chapter_start, chapter_end, chapter_count, est_minutes) VALUES ('ra-16-john-18', 16, 'John', 18, 21, 4, 16);
INSERT INTO reading_assignments (id, day_number, book, chapter_start, chapter_end, chapter_count, est_minutes) VALUES ('ra-16-acts-1', 16, 'Acts', 1, 1, 1, 10);
INSERT INTO reading_days (day_number, date, label) VALUES (17, '2026-09-30', 'Reading Day 17');
INSERT INTO reading_assignments (id, day_number, book, chapter_start, chapter_end, chapter_count, est_minutes) VALUES ('ra-17-acts-2', 17, 'Acts', 2, 6, 5, 20);
INSERT INTO reading_days (day_number, date, label) VALUES (18, '2026-10-01', 'Reading Day 18');
INSERT INTO reading_assignments (id, day_number, book, chapter_start, chapter_end, chapter_count, est_minutes) VALUES ('ra-18-acts-7', 18, 'Acts', 7, 11, 5, 20);
INSERT INTO reading_days (day_number, date, label) VALUES (19, '2026-10-03', 'Reading Day 19');
INSERT INTO reading_assignments (id, day_number, book, chapter_start, chapter_end, chapter_count, est_minutes) VALUES ('ra-19-acts-12', 19, 'Acts', 12, 16, 5, 20);
INSERT INTO reading_days (day_number, date, label) VALUES (20, '2026-10-04', 'Reading Day 20');
INSERT INTO reading_assignments (id, day_number, book, chapter_start, chapter_end, chapter_count, est_minutes) VALUES ('ra-20-acts-17', 20, 'Acts', 17, 21, 5, 20);
INSERT INTO reading_days (day_number, date, label) VALUES (21, '2026-10-05', 'Reading Day 21');
INSERT INTO reading_assignments (id, day_number, book, chapter_start, chapter_end, chapter_count, est_minutes) VALUES ('ra-21-acts-22', 21, 'Acts', 22, 26, 5, 20);
INSERT INTO reading_days (day_number, date, label) VALUES (22, '2026-10-07', 'Reading Day 22');
INSERT INTO reading_assignments (id, day_number, book, chapter_start, chapter_end, chapter_count, est_minutes) VALUES ('ra-22-acts-27', 22, 'Acts', 27, 28, 2, 10);
INSERT INTO reading_assignments (id, day_number, book, chapter_start, chapter_end, chapter_count, est_minutes) VALUES ('ra-22-romans-1', 22, 'Romans', 1, 3, 3, 12);
INSERT INTO reading_days (day_number, date, label) VALUES (23, '2026-10-08', 'Reading Day 23');
INSERT INTO reading_assignments (id, day_number, book, chapter_start, chapter_end, chapter_count, est_minutes) VALUES ('ra-23-romans-4', 23, 'Romans', 4, 8, 5, 20);
INSERT INTO reading_days (day_number, date, label) VALUES (24, '2026-10-10', 'Reading Day 24');
INSERT INTO reading_assignments (id, day_number, book, chapter_start, chapter_end, chapter_count, est_minutes) VALUES ('ra-24-romans-9', 24, 'Romans', 9, 13, 5, 20);
INSERT INTO reading_days (day_number, date, label) VALUES (25, '2026-10-11', 'Reading Day 25');
INSERT INTO reading_assignments (id, day_number, book, chapter_start, chapter_end, chapter_count, est_minutes) VALUES ('ra-25-romans-14', 25, 'Romans', 14, 16, 3, 12);
INSERT INTO reading_assignments (id, day_number, book, chapter_start, chapter_end, chapter_count, est_minutes) VALUES ('ra-25-1corinthians-1', 25, '1 Corinthians', 1, 2, 2, 10);
INSERT INTO reading_days (day_number, date, label) VALUES (26, '2026-10-12', 'Reading Day 26');
INSERT INTO reading_assignments (id, day_number, book, chapter_start, chapter_end, chapter_count, est_minutes) VALUES ('ra-26-1corinthians-3', 26, '1 Corinthians', 3, 7, 5, 20);
INSERT INTO reading_days (day_number, date, label) VALUES (27, '2026-10-14', 'Reading Day 27');
INSERT INTO reading_assignments (id, day_number, book, chapter_start, chapter_end, chapter_count, est_minutes) VALUES ('ra-27-1corinthians-8', 27, '1 Corinthians', 8, 12, 5, 20);
INSERT INTO reading_days (day_number, date, label) VALUES (28, '2026-10-15', 'Reading Day 28');
INSERT INTO reading_assignments (id, day_number, book, chapter_start, chapter_end, chapter_count, est_minutes) VALUES ('ra-28-1corinthians-13', 28, '1 Corinthians', 13, 16, 4, 16);
INSERT INTO reading_assignments (id, day_number, book, chapter_start, chapter_end, chapter_count, est_minutes) VALUES ('ra-28-2corinthians-1', 28, '2 Corinthians', 1, 1, 1, 10);
INSERT INTO reading_days (day_number, date, label) VALUES (29, '2026-10-17', 'Reading Day 29');
INSERT INTO reading_assignments (id, day_number, book, chapter_start, chapter_end, chapter_count, est_minutes) VALUES ('ra-29-2corinthians-2', 29, '2 Corinthians', 2, 6, 5, 20);
INSERT INTO reading_days (day_number, date, label) VALUES (30, '2026-10-18', 'Reading Day 30');
INSERT INTO reading_assignments (id, day_number, book, chapter_start, chapter_end, chapter_count, est_minutes) VALUES ('ra-30-2corinthians-7', 30, '2 Corinthians', 7, 11, 5, 20);
INSERT INTO reading_days (day_number, date, label) VALUES (31, '2026-10-19', 'Reading Day 31');
INSERT INTO reading_assignments (id, day_number, book, chapter_start, chapter_end, chapter_count, est_minutes) VALUES ('ra-31-2corinthians-12', 31, '2 Corinthians', 12, 13, 2, 10);
INSERT INTO reading_assignments (id, day_number, book, chapter_start, chapter_end, chapter_count, est_minutes) VALUES ('ra-31-galatians-1', 31, 'Galatians', 1, 3, 3, 12);
INSERT INTO reading_days (day_number, date, label) VALUES (32, '2026-10-21', 'Reading Day 32');
INSERT INTO reading_assignments (id, day_number, book, chapter_start, chapter_end, chapter_count, est_minutes) VALUES ('ra-32-galatians-4', 32, 'Galatians', 4, 6, 3, 12);
INSERT INTO reading_assignments (id, day_number, book, chapter_start, chapter_end, chapter_count, est_minutes) VALUES ('ra-32-ephesians-1', 32, 'Ephesians', 1, 2, 2, 10);
INSERT INTO reading_days (day_number, date, label) VALUES (33, '2026-10-22', 'Reading Day 33');
INSERT INTO reading_assignments (id, day_number, book, chapter_start, chapter_end, chapter_count, est_minutes) VALUES ('ra-33-ephesians-3', 33, 'Ephesians', 3, 6, 4, 16);
INSERT INTO reading_assignments (id, day_number, book, chapter_start, chapter_end, chapter_count, est_minutes) VALUES ('ra-33-philippians-1', 33, 'Philippians', 1, 1, 1, 10);
INSERT INTO reading_days (day_number, date, label) VALUES (34, '2026-10-24', 'Reading Day 34');
INSERT INTO reading_assignments (id, day_number, book, chapter_start, chapter_end, chapter_count, est_minutes) VALUES ('ra-34-philippians-2', 34, 'Philippians', 2, 4, 3, 12);
INSERT INTO reading_assignments (id, day_number, book, chapter_start, chapter_end, chapter_count, est_minutes) VALUES ('ra-34-colossians-1', 34, 'Colossians', 1, 2, 2, 10);
INSERT INTO reading_days (day_number, date, label) VALUES (35, '2026-10-25', 'Reading Day 35');
INSERT INTO reading_assignments (id, day_number, book, chapter_start, chapter_end, chapter_count, est_minutes) VALUES ('ra-35-colossians-3', 35, 'Colossians', 3, 4, 2, 10);
INSERT INTO reading_assignments (id, day_number, book, chapter_start, chapter_end, chapter_count, est_minutes) VALUES ('ra-35-1thessalonians-1', 35, '1 Thessalonians', 1, 3, 3, 12);
INSERT INTO reading_days (day_number, date, label) VALUES (36, '2026-10-26', 'Reading Day 36');
INSERT INTO reading_assignments (id, day_number, book, chapter_start, chapter_end, chapter_count, est_minutes) VALUES ('ra-36-1thessalonians-4', 36, '1 Thessalonians', 4, 5, 2, 10);
INSERT INTO reading_assignments (id, day_number, book, chapter_start, chapter_end, chapter_count, est_minutes) VALUES ('ra-36-2thessalonians-1', 36, '2 Thessalonians', 1, 3, 3, 12);
INSERT INTO reading_days (day_number, date, label) VALUES (37, '2026-10-28', 'Reading Day 37');
INSERT INTO reading_assignments (id, day_number, book, chapter_start, chapter_end, chapter_count, est_minutes) VALUES ('ra-37-1timothy-1', 37, '1 Timothy', 1, 5, 5, 20);
INSERT INTO reading_days (day_number, date, label) VALUES (38, '2026-10-29', 'Reading Day 38');
INSERT INTO reading_assignments (id, day_number, book, chapter_start, chapter_end, chapter_count, est_minutes) VALUES ('ra-38-1timothy-6', 38, '1 Timothy', 6, 6, 1, 10);
INSERT INTO reading_assignments (id, day_number, book, chapter_start, chapter_end, chapter_count, est_minutes) VALUES ('ra-38-2timothy-1', 38, '2 Timothy', 1, 4, 4, 16);
INSERT INTO reading_days (day_number, date, label) VALUES (39, '2026-10-31', 'Reading Day 39');
INSERT INTO reading_assignments (id, day_number, book, chapter_start, chapter_end, chapter_count, est_minutes) VALUES ('ra-39-titus-1', 39, 'Titus', 1, 3, 3, 12);
INSERT INTO reading_assignments (id, day_number, book, chapter_start, chapter_end, chapter_count, est_minutes) VALUES ('ra-39-philemon-1', 39, 'Philemon', 1, 1, 1, 10);
INSERT INTO reading_assignments (id, day_number, book, chapter_start, chapter_end, chapter_count, est_minutes) VALUES ('ra-39-hebrews-1', 39, 'Hebrews', 1, 1, 1, 10);
INSERT INTO reading_days (day_number, date, label) VALUES (40, '2026-11-01', 'Reading Day 40');
INSERT INTO reading_assignments (id, day_number, book, chapter_start, chapter_end, chapter_count, est_minutes) VALUES ('ra-40-hebrews-2', 40, 'Hebrews', 2, 6, 5, 20);
INSERT INTO reading_days (day_number, date, label) VALUES (41, '2026-11-02', 'Reading Day 41');
INSERT INTO reading_assignments (id, day_number, book, chapter_start, chapter_end, chapter_count, est_minutes) VALUES ('ra-41-hebrews-7', 41, 'Hebrews', 7, 11, 5, 20);
INSERT INTO reading_days (day_number, date, label) VALUES (42, '2026-11-04', 'Reading Day 42');
INSERT INTO reading_assignments (id, day_number, book, chapter_start, chapter_end, chapter_count, est_minutes) VALUES ('ra-42-hebrews-12', 42, 'Hebrews', 12, 13, 2, 10);
INSERT INTO reading_assignments (id, day_number, book, chapter_start, chapter_end, chapter_count, est_minutes) VALUES ('ra-42-james-1', 42, 'James', 1, 3, 3, 12);
INSERT INTO reading_days (day_number, date, label) VALUES (43, '2026-11-05', 'Reading Day 43');
INSERT INTO reading_assignments (id, day_number, book, chapter_start, chapter_end, chapter_count, est_minutes) VALUES ('ra-43-james-4', 43, 'James', 4, 5, 2, 10);
INSERT INTO reading_assignments (id, day_number, book, chapter_start, chapter_end, chapter_count, est_minutes) VALUES ('ra-43-1peter-1', 43, '1 Peter', 1, 3, 3, 12);
INSERT INTO reading_days (day_number, date, label) VALUES (44, '2026-11-07', 'Reading Day 44');
INSERT INTO reading_assignments (id, day_number, book, chapter_start, chapter_end, chapter_count, est_minutes) VALUES ('ra-44-1peter-4', 44, '1 Peter', 4, 5, 2, 10);
INSERT INTO reading_assignments (id, day_number, book, chapter_start, chapter_end, chapter_count, est_minutes) VALUES ('ra-44-2peter-1', 44, '2 Peter', 1, 3, 3, 12);
INSERT INTO reading_days (day_number, date, label) VALUES (45, '2026-11-08', 'Reading Day 45');
INSERT INTO reading_assignments (id, day_number, book, chapter_start, chapter_end, chapter_count, est_minutes) VALUES ('ra-45-1john-1', 45, '1 John', 1, 5, 5, 20);
INSERT INTO reading_days (day_number, date, label) VALUES (46, '2026-11-09', 'Reading Day 46');
INSERT INTO reading_assignments (id, day_number, book, chapter_start, chapter_end, chapter_count, est_minutes) VALUES ('ra-46-2john-1', 46, '2 John', 1, 1, 1, 10);
INSERT INTO reading_assignments (id, day_number, book, chapter_start, chapter_end, chapter_count, est_minutes) VALUES ('ra-46-3john-1', 46, '3 John', 1, 1, 1, 10);
INSERT INTO reading_assignments (id, day_number, book, chapter_start, chapter_end, chapter_count, est_minutes) VALUES ('ra-46-jude-1', 46, 'Jude', 1, 1, 1, 10);
INSERT INTO reading_assignments (id, day_number, book, chapter_start, chapter_end, chapter_count, est_minutes) VALUES ('ra-46-revelation-1', 46, 'Revelation', 1, 2, 2, 10);
INSERT INTO reading_days (day_number, date, label) VALUES (47, '2026-11-11', 'Reading Day 47');
INSERT INTO reading_assignments (id, day_number, book, chapter_start, chapter_end, chapter_count, est_minutes) VALUES ('ra-47-revelation-3', 47, 'Revelation', 3, 7, 5, 20);
INSERT INTO reading_days (day_number, date, label) VALUES (48, '2026-11-12', 'Reading Day 48');
INSERT INTO reading_assignments (id, day_number, book, chapter_start, chapter_end, chapter_count, est_minutes) VALUES ('ra-48-revelation-8', 48, 'Revelation', 8, 12, 5, 20);
INSERT INTO reading_days (day_number, date, label) VALUES (49, '2026-11-14', 'Reading Day 49');
INSERT INTO reading_assignments (id, day_number, book, chapter_start, chapter_end, chapter_count, est_minutes) VALUES ('ra-49-revelation-13', 49, 'Revelation', 13, 17, 5, 20);
INSERT INTO reading_days (day_number, date, label) VALUES (50, '2026-11-15', 'Reading Day 50');
INSERT INTO reading_assignments (id, day_number, book, chapter_start, chapter_end, chapter_count, est_minutes) VALUES ('ra-50-revelation-18', 50, 'Revelation', 18, 22, 5, 20);
